name: Docker Hub REG

on:
  push:
    branches:
      - 'master'

jobs:
  docker-hub-reg:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKERHUBREG }}
          username: ${{ secrets.DOCKERHUBREG_USERNAME }}
          password: ${{ secrets.DOCKERHUBREG_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ secrets.DOCKERHUBREG_TAG }}
